services:
  - type: web
    name: crud-usuarios
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "node src/index.js"
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false # vamos adicionar manualmente pelo painel do Render
